packages:
  - packages/*

patchedDependencies:
  on-change: patches/on-change.patch

onlyBuiltDependencies:
  - esbuild
  - unrs-resolver

publicHoistPattern:
  - eslint-plugin-*
  - '@prettier/plugin-*'
